### ISSUE TITLE
Length, spacing ignored for unary operator "not"

### ISSUE THREAD

**Issue by rcrogers** [jimweirich/sorcerer#2]
```
Sorcerer.source Ripper.sexp_raw "not true"
=> "ntrue"
```

Looks like the problem originates here:

```
  :unary => lambda { |sexp|
    emit(sexp[1].to_s[0,1])
    resource(sexp[2])
  },
```

There is a simple workaround -- changing :not to :! in the Ripper s-expression before converting back to source.

By the way, this gem is awesome.

**Comment by jimweirich** [comment]
Fixed the unary handler to properly handle "not" expressions.  Thanks for the catch.

Fixed in version 0.3.3.
