### ISSUE TITLE
Handler for mrhs_new not implemented 

### ISSUE THREAD

**Issue by brueckenschlaeger23** [jimweirich/sorcerer#3]
As mentioned in the title, the handler for a new right asterisk operation is not implemented (see resource.rb ":mrhs_new => NYI"). See an example where ripper creates mrhs_new:

```
args = [:a, :b, nil]
t = *args
```

or even simplier

```
"a = *[:a, :b]"
```

(although it does not make sense in this examples)

Actually, :mrhs_add_star already works so it seems you may simply ignore it. E.g. it works for me if I simply change line 667

```
 :mrhs_add_star => lambda { |sexp|
    resource(sexp[1])
```

adding an "unless sexp[1] == :mrhs_new

Any chance to add / ignore this handler ?

**Comment by jimweirich** [comment]
Fixed in 0.3.5.  Gem is built and pushed.  Thanks for the report.
