### ISSUE TITLE
def meth args={} will result in missing space

### ISSUE THREAD

**Issue by brueckenschlaeger23** [jimweirich/sorcerer#4]
First, thanks a lot for your fast response and fix!

If you parse 

```
def meth args={}
end
```

 with ripper, it results in the following sexp

```
[:params, nil, [[[:@ident, "args", [1, 9]], [:hash, nil]]], nil, nil, nil]
```

causing the method params_are_empty? (resource.rb:119) to return true and the result 

```
def methargs={}
end
```

misses a space.

Another thing, do you plan to add an option like for multiline and indent to add parenthesis always (unless empty)?

**Comment by jimweirich** [comment]
Thanks.  Also found a couple more bugs in the same area.  It is fixed on master and I'll release a new version soon.

**Comment by jimweirich** [comment]
Hadn't planned on a optional parenthesis flag.  The reason is that the parens are explicit in the sexps and the indent and lines are not.

**Comment by jimweirich** [comment]
New gem (0.3.10) has been pushed. 

BTW, sorry about the delay on this issue.
